# 1. Name of workflow
name: Unit Tests

# 2. When to run workflow
on:
  pull_request:
  push:
    branches:
      - develop
  merge_group:

# 3. Jobs to run (in parallel)
jobs:

  # 3.1. Job name (internal)
  test:

    # 3.2. Job name (external)
    name: Unit Tests

    # 3.3. Runner OS (can be Windows, macOS, or Linux)
    runs-on: ubuntu-latest

    # 3.4. Sequential steps in job
    steps:

      # 3.4.1. Checkout code
      - name: üõé Checkout
        uses: actions/checkout@v3

      # 3.4.2. Install and setup Python
      - name: üêç Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: API/pyproject.toml
          # cache: 'pip'

      # 3.4.3. Install Poetry
      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version
          
      # Install dependencies (if any). They will be cached with saved for next time with the cache command above

      - name: Install
        run: pip install API/.

      # 3.4.4. Run tests (execute arbitrary commands in shell)
      - name: üèÉRun tests
        run: pytest API